---
exclude_paths:
  - ".github/**"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**.yml"
  - "**.md"
  - "**.d.ts"
  - "gh-pages-out/**"
  - "public/**"
  - ".vscode/**"
  - "**.json"
  - "**.config.**"
  - "playlist_stats_viewer.html"
  - "src/test/*.ts"
  - "src/types/*.ts"
