name: ⏳ Add backlog entry
description: Add a new backlog entry into the database
title: '[ADD_BACKLOG] '
labels: ["database","[ADD_BACKLOG]"]
body:

  - type: markdown
    attributes:
      value: |
        Please fill in the following fields to add this game into database !

  - type: input
    id: title
    attributes:
      label: Name of the game
      description: What is the game name in the language it was played ?
      placeholder: ex. Splinter Cell HD
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: On which platform was the content on ?
      options:
        - PC
        - GBA
        - PSP
        - PS1
        - PS2
        - PS3

  - type: input
    id: hltb_main
    attributes:
      label: Main Story Duration
      description: Expected format HH:mm:ss (Leave empty for auto-sync)
      placeholder: "08:30:00"
  
  - type: input
    id: hltb_extra
    attributes:
      label: Main + Extra Duration
      description: Expected format HH:mm:ss (Leave empty for auto-sync)
      placeholder: "12:00:00"

  - type: input
    id: hltb_completionist
    attributes:
      label: Completionist Duration
      description: Expected format HH:mm:ss (Leave empty for auto-sync)
      placeholder: "25:45:00"
      
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Additional notes or comments about the game
