name: 🖌️ Update test
description: Update a existing test fields into the database
title: '[UPDATE_TEST] '
labels: ["database","[UPDATE_TEST]"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill in the following fields to update this test into database !
  - type: dropdown
    id: identifierKind
    attributes:
      label: Kind of content
      description: Is it a playlist or a video ?
      options:
        - Playlist
        - Video
      default: 0
  - type: input
    id: identifierValue
    attributes:
      label: Identifier
      description: What is the test playlist ID or video ID on Youtube ?
      placeholder: >-
        ex. PLRfhDHeBTBJ56jE5Kb3Wb6vBZZKLgM0dR or dn6QTMujBiY
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: Name of the test
      description: What is the test name in the language it was played ?
      placeholder: ex. Splinter Cell HD
  - type: input
    id: releaseDate
    attributes:
      label: Release Date
      description: When was this test published ?
      placeholder: YYYY-MM-DD
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: On which platform was the content on ?
      options:
        - PC
        - GBA
        - PSP
        - PS1
        - PS2
        - PS3
  - type: input
    id: duration
    attributes:
      label: Duration of the test
      description: >-
        How long is that test ? Express it with ISO 8601 time notation
        (HH:MM:SS)
      placeholder: '02:23:15'
