name: 🚮 Delete test
description: Delete a test from the database
title: '[DELETE_TEST] '
labels: ["database","[DELETE_TEST]"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill in the following fields to delete this test out of database !
  - type: dropdown
    id: identifierKind
    attributes:
      label: Kind of content
      description: Is it a playlist or a video ?
      options:
        - Playlist
        - Video
      default: 0
  - type: input
    id: identifierValue
    attributes:
      label: Identifier
      description: What is the test playlist ID or video ID on Youtube ?
      placeholder: >-
        ex. PLRfhDHeBTBJ56jE5Kb3Wb6vBZZKLgM0dR or dn6QTMujBiY
    validations:
      required: true
