name: Auto Merge PRs

on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    steps:
      - name: Auto merge PRs
        uses: peter-evans/enable-pull-request-automerge@v3.0.0
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.PAT }}
