name: Convert all pictures to Webp
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.jpg'
      - '**.png'
      - '**.jpeg'
      - '**.webp'
jobs:
  convert_all_to_webp:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v6
          with:
            ref: ${{ github.head_ref }}
        - name: Install WEBP converter
          run: | 
            sudo apt-get update && sudo apt install webp
            sudo chmod ugo+x .github/workflows/toWebp
        - name: Convert every picture to webp (and replace references)
          run: |
            sudo ./.github/workflows/toWebp public
            sudo ./.github/workflows/toWebp src
        - name: Compress pictures
          uses: calibreapp/image-actions@main
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ignorePaths: 'node_modules/**,build'
            compressOnly: true
        - name: Create Pull Request 🤖
          if: always()
          uses: peter-evans/create-pull-request@v8
          with:
            token: ${{ secrets.PAT }}
            commit-message: "chore: convert images to webp and optimize"
            branch: auto-webp-optimization
            title: "Optimize Images: Convert to WebP"
            labels: |
             automerge
            body: |
              ## Image Optimization Report 🚀
              This PR was automatically generated to:
              * Convert `.jpg`, `.png`, and `.jpeg` files to `.webp`.
              * Replace internal references in `src` and `public`.
              * Apply compression using `calibreapp/image-actions`.
  
              @coderabbitai ignore
