name: Lighthouse Github Pages
on:
# Only for on pull request event
  pull_request:
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: mkdir -p ${{ github.workspace }}/tmp/artifacts
    - name: Waiting for Vercel Preview
      uses: patrickedqvist/wait-for-vercel-preview@v1.2.0
      id: vercelPreview
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        max_timeout: 90 # Wait for 90 seconds before failing
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        outputDirectory: ${{ github.workspace }}/tmp/artifacts
        gitAuthor: ${{ github.actor }}
        gitBranch: ${{ github.ref }}
        gitHubAccessToken: ${{ secrets.GITHUB_TOKEN }}
        prCommentEnabled: true
        device: "all"
        locale: "fr"
        urls: "https://jy95.github.io/?/games,${{ steps.vercelPreview.outputs.url }}/games"
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: Lighthouse reports
        path: ${{ github.workspace }}/tmp/artifacts