name: Lighthouse Compare Action
on:
  pull_request:

jobs:
  getPreviewUrl:
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.branch-preview-url.outputs.url }}
    steps:
      - uses: actions/checkout@v4
      - name: Generate branch preview URL
        id: branch-preview-url
        uses: PenfoldTechnology/vercel-branch-preview-url-action@v2.0.0
        with:
          git-branch-name: ${{ github.head_ref || github.ref_name }}
          vercel-project-name: gpfr
          vercel-team-id: jy95s-projects
      - name: Print URL
        run: echo "${{ steps.branch-preview-url.outputs.url }}"
      #- name: Wait for preview url to be ready
        

  lighthouse:
    needs: getPreviewUrl
    runs-on: ubuntu-latest
    env:
      # Subpaths to investigate
      SUBPATHS: "/games,/games/series,/games/dlcs,/planning,/backlog,/tests,/stats,/links"
    steps:
      - uses: actions/checkout@v4
      - name: Construct URLs
        id: construct_urls
        run: |
          URL_LIST=$(echo "${{ env.SUBPATHS }}" | tr ',' '\n' | sed "s|^|${{ needs.getPreviewUrl.outputs.preview_url }}|g" | tr '\n' ', ')
          echo "url_list=$URL_LIST" >> $GITHUB_OUTPUT
      - uses: foo-software/lighthouse-check-action@master
        with:
          urls: ${{ steps.construct_urls.outputs.url_list }}
          prCommentEnabled: true
