name: Lighthouse Github Pages
on:
# Only for on pull request event
  pull_request:
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: mkdir -p ${{ github.workspace }}/tmp/artifacts
    - uses: UnlyEd/github-action-await-vercel@v1.2.14
      id: await-vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      with:
        deployment-url: jy95-github-io.vercel.app # TODO Replace by the domain you want to test
        timeout: 90 # Wait for 90 seconds before failing
    - name: Display deployment status
      run: "echo The deployment at ${{ fromJson(steps.await-vercel.outputs.deploymentDetails).url }} is ${{ fromJson(steps.await-vercel.outputs.deploymentDetails).readyState }}"
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        outputDirectory: ${{ github.workspace }}/tmp/artifacts
        gitAuthor: ${{ github.actor }}
        gitBranch: ${{ github.ref }}
        gitHubAccessToken: ${{ secrets.GITHUB_TOKEN }}
        prCommentEnabled: true
        urls: "https://jy95.github.io/?/games,https://${{ fromJson(steps.await-vercel.outputs.deploymentDetails).url }}/games"
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: Lighthouse reports
        path: ${{ github.workspace }}/tmp/artifacts