name: Sync Database Views

on:
  push:
    branches:
      - master
    paths:
      - 'scripts/views/**/*.sql'

jobs:
  sync-views:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v7

      - name: Setup Node.js ✨
        uses: actions/setup-node@v7
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci

      - name: Sync views into SQLite DB
        run: npm run db:sync-views

      - name: Create Pull Request for updated DB
        uses: peter-evans/create-pull-request@v8
        with:
            commit-message: "chore(db): sync database views from db/views/"
            title: "chore(db): auto-sync database views"
            body: |
                This PR was automatically created by GitHub Actions after updates to the SQL view definitions in `scripts/views/`.
                
                - Applied SQL views to the database file.
                - Please review if tests are failling.

                @coderabbitai ignore
            branch: "automated/auto-sync-db-views"
            delete-branch: true
            labels: |
                database
                automerge
